spring:
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 500
  h2:
    console:
      enabled: false
  flyway:
    enabled: false

security:
  jwt:
    token:
      secret-key: cvi_secret_key
      expire-length: 3600000

  auth:
    naver:
      client-secret: client-secret

  public:
    data:
      vaccination: publicdata-secret

server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
---
spring:
  config:
    activate:
      on-profile: deploy1

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: deploy2

server:
  port: 8082
