spring:
  profiles:
    active: local

  jpa:
    properties:
      hibernate.default_batch_fetch_size: 500
  h2:
    console:
      enabled: false
  flyway:
    enabled: false

  cache:
    jcache:
      config: classpath:ehcache.xml

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB

security:
  jwt:
    token:
      secret-key: cvi_secret_key
      expire-length: 3600000

  auth:
    naver:
      client-secret: client-secret

  public:
    data:
      vaccination: publicdata-secret

aws:
  s3:
    bucket_name: bucket-name
    directory:
      path:
        posts:
          images: dir-path
  cloudfront:
    url: https://cloudfront.net

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - file:./cvi-backend-secret/application-publicdata-secret.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  flyway:
    enabled: false
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: debug
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.hibernate.SQL: debug
---
spring:
  config:
    activate:
      on-profile: deploy1

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: deploy2

server:
  port: 8082
