spring:
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 500
  h2:
    console:
      enabled: false
  flyway:
    enabled: false

  cache:
    jcache:
      config: classpath:ehcache.xml

security:
  jwt:
    token:
      secret-key: cvi_secret_key
      expire-length: 3600000

  auth:
    naver:
      client-secret: client-secret

  public:
    data:
      vaccination: publicdata-secret

cloud:
  aws:
    credentials:
      accessKey: access-key
      secretKey: access-key
    s3:
      bucket: bucket-name
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
---
spring:
  config:
    activate:
      on-profile: deploy1

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: deploy2

server:
  port: 8082
