spring:
  profiles:
    include:
      - domain-cvi
      - domain-cvi-oauth
      - domain-cvi-publicdata

  cache:
    jcache:
      config: classpath:ehcache.xml

security:
  jwt:
    token:
      secret-key: cvi_secret_key
      expire-length: 3600000

server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: deploy1

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: deploy2

server:
  port: 8082
